FROM centos:7

# 1. Add PHP 7.3 Remi repository
RUN yum -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm 
RUN yum -y install epel-release yum-utils

# 2: Disable repo for PHP 5.4
RUN yum-config-manager --disable remi-php54
RUN yum-config-manager --enable remi-php73

# 3: Install PHP 7.3 on CentOS 7 / Fedora
RUN yum -y install php php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json

WORKDIR /var/www/html/

COPY . .